version: '3.9'

services:
  builds-docs:
    image: node:18-alpine
    volumes:
      - ./:/home/node
    environment:
      TEST: 1
    working_dir: /home/node
    entrypoint: npm
    command: run build
