version: '3.9'

services:
  builds-docs:
    image: node:18-alpine
    volumes:
      - ./:/tmp/docs
    environment:
      PROD: 1
      GA_ID: $GA_ID
    working_dir: /tmp/docs
    entrypoint: npm
    command: run build
