version: '3.9'

services:
  deploy_docs:
    image: node:17.8
    volumes:
      - ./:/home/docs
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - USER=$USER
      - ORG=$ORG
      - REPO=$REPO
      - PROD=1
      - NODE_OPTIONS=--openssl-legacy-provider
    working_dir: '/home/docs'
    entrypoint: ['sh']
    command: [-c, "npm install && npm run build"]
